module.exports = {
  RECEIVE_COLLECTION: "RECEIVE_COLLECTION",
  RECEIVE_COLLECTIONS: "RECEIVE_COLLECTIONS",
  RECEIVE_MODAL_COLLECTION: "RECEIVE_MODAL_COLLECTION",
  RECEIVE_ADDED_PHOTO: "RECEIVE_ADDED_PHOTO",
  REMOVE_ADDED_PHOTO: "REMOVE_ADDED_PHOTO"
}
